data:
  name: spdc
  datapath: '/home/dor-hay.sha/project/data/spdc/fixed_pump_10.bin'
  total_num: 10
  offset: 0
  n_sample: 8
  nx: 121
  ny: 121
  nz: 10
  sub_xy: 3
  sub_z: 1
  nin: 3
  nout: 2

model:
  layers: [64, 64, 64, 64, 64]
  modes1: [8, 8, 8, 8]
  modes2: [8, 8, 8, 8]
  modes3: [8, 8, 8, 8]
  fc_dim: 128
  in_dim: 9
  out_dim: 4
  act: gelu
  num_pad: 5

train:
  batchsize: 1
  epochs: 500
  milestones: [150, 300, 450]
  base_lr: 0.001
  scheduler_gamma: 0.5
  ic_loss: 1.0
  f_loss: 1.0
  xy_loss: 5.0
  save_dir: 'spdc-FDM'
  save_name: 'spdc-pino-eqn.pt'

log:
  project: PINO-spdc-test
  group: gelu-eqn
  entity: hzzheng-pino

