data:
  name: spdc
  datapath: '/home/dor-hay.sha/project/data/spdc/random_pump_N-100_seed-1701_spp-1.bin'
  total_num: 100
  offset: 0
  n_sample: 80
  spp: 1
  nx: 121
  ny: 121
  nz: 10
  sub_xy: 4
  sub_z: 1
  subsample_xy: 3
  nin: 3
  nout: 2

model:
  layers: [64, 64, 64, 64, 64]
  modes1: [8, 8, 8, 8]
  modes2: [8, 8, 8, 8]
  modes3: [8, 8, 8, 8]
  fc_dim: 128
  in_dim: 9
  out_dim: 4
  act: gelu
  num_pad: 5
  grad: 'none'

train:
  batchsize: 1
  epochs: 1
  milestones: [1]
  base_lr: 0.001
  scheduler_gamma: 0.5
  ic_loss: 0.0
  f_loss: 0.0
  xy_loss: 1.0
  save_dir: 'spdc-FDM'
  save_name: 'spdc-pump-random_N-100_spp-1_ratio-inf_subsample-30.pt'

log:
  project: PINO-spdc-test
  group: ml4physics_spdc
  entity: ml4physics_spdc
  tags: ["random_pump", "N-100", "spp-10", "ratio-inf", "subsample-30"]
